CREATE OR REPLACE TABLE TRANSPORTATION_HUB.HUB.MESSAGE (
	MESSAGE_UID NUMBER(38,0) NOT NULL DEFAULT TRANSPORTATION_HUB.HUB.MESSAGE_SEQ.NEXTVAL,
	MESSAGE_ID NUMBER(38,0),
	SIGN_MESSAGE VARCHAR(50),
	SIGN_MESSAGE_LONG VARCHAR(100),
	CONSTRAINT PK_MESSAGE_ID PRIMARY KEY (MESSAGE_UID)
);