CREATE  TABLE TRANSPORTATION_HUB.HUB.PATTERNS ( 
	PATTERN_ID           number(38,0) NOT NULL    ,
	CONSTRAINT UNQ_PATTERNS_PATTERN_ID UNIQUE ( PATTERN_ID ),
	CONSTRAINT PK_PATTERNS_PATTERN_ID PRIMARY KEY ( PATTERN_ID )
 );
