CREATE OR REPLACE TABLE TRANSPORTATION_HUB.HUB.ROUTE (
	ROUTE_UID NUMBER(38,0) NOT NULL DEFAULT TRANSPORTATION_HUB.HUB.ROUTE_SEQ.NEXTVAL,
	ROUTE_ID NUMBER(38,0),
	ROUTE_TYPE VARCHAR(10),
	ROUTE_SUB_TYPE VARCHAR(20),
	ROUTE_COLOR VARCHAR(6),
	FREQUENT_SERVICE BOOLEAN,
	ROUTE_DESC VARCHAR(50),
	CONSTRAINT PK_ROUTE_ID PRIMARY KEY (ROUTE_UID)
);