CREATE  TABLE TRANSPORTATION_HUB.HUB.SCHEDULES ( 
	SCHEDULE_ID          number(38,0) NOT NULL    ,
	ROUTE_ID             number(38,0) NOT NULL    ,
	STOP_ID              number(38,0) NOT NULL    ,
	DIRECTION            varchar     ,
	DAY_TYPE             varchar     ,
	DAY_OF_WEEK          varchar     ,
	SCHEDULED_ARRIVAL_TIME timestamp_ntz(9)     ,
	SCHEDULED_DEPARTURE_TIME timestamp_ntz(9)     ,
	CONSTRAINT PK_SCHEDULES_SCHEDULE_ID PRIMARY KEY ( SCHEDULE_ID )
 );

ALTER TABLE TRANSPORTATION_HUB.HUB.SCHEDULES ADD CONSTRAINT FK_SCHEDULES_STOPS FOREIGN KEY ( STOP_ID ) REFERENCES TRANSPORTATION_HUB.HUB.STOPS( STOP_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;
