CREATE  TABLE TRANSPORTATION_HUB.HUB.TRIPS ( 
	TRIP_ID              number(38,0) NOT NULL    ,
	VEHICLE_ID           number(38,0) NOT NULL    ,
	ROUTE_ID             number(38,0) NOT NULL    ,
	PATTERN_ID           number(38,0) NOT NULL    ,
	CONSTRAINT PK_TRIP_TRIP_ID PRIMARY KEY ( TRIP_ID )
 );

ALTER TABLE TRANSPORTATION_HUB.HUB.TRIPS ADD CONSTRAINT FK_TRIP_PATTERNS FOREIGN KEY ( PATTERN_ID ) REFERENCES TRANSPORTATION_HUB.HUB.PATTERNS( PATTERN_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE TRANSPORTATION_HUB.HUB.TRIPS ADD CONSTRAINT FK_TRIP_ROUTE FOREIGN KEY ( ROUTE_ID ) REFERENCES TRANSPORTATION_HUB.HUB.ROUTES( ROUTE_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE TRANSPORTATION_HUB.HUB.TRIPS ADD CONSTRAINT FK_TRIP_VEHICLE FOREIGN KEY ( VEHICLE_ID ) REFERENCES TRANSPORTATION_HUB.HUB.VEHICLES( VEHICLE_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;
