CREATE  TABLE TRANSPORTATION_HUB.HUB.VEHICLE_POSITIONS ( 
	VEHICLE_POSITION_ID  number(38,0) NOT NULL DEFAULT VEHICLE_POSITION_SEQ.NEXTVAL   ,
	VEHICLE_ID           number(38,0) NOT NULL    ,
	"DATETIME"           timestamp_ntz(9) NOT NULL    ,
	LATITUDE             number(15,12) NOT NULL    ,
	LONGITUDE            number(15,12) NOT NULL    ,
	ROUTE_ID             number(38,0) NOT NULL    ,
	TRIP_ID              number(38,0) NOT NULL    ,
	LAST_STOP_ID         number(38,0) NOT NULL    ,
	NEXT_STOP_ID         number(38,0) NOT NULL    ,
	IN_CONGESTION        boolean     ,
	OFF_ROUTE            boolean     ,
	MESSAGE_ID           number(38,0)     ,
	CONSTRAINT PK_VEHICLE_POSITION_ID PRIMARY KEY ( VEHICLE_POSITION_ID )
 );

ALTER TABLE TRANSPORTATION_HUB.HUB.VEHICLE_POSITION ADD CONSTRAINT FK_VEHICLE_POSITION_STOPS FOREIGN KEY ( NEXT_STOP_ID ) REFERENCES TRANSPORTATION_HUB.HUB.STOPS( STOP_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE TRANSPORTATION_HUB.HUB.VEHICLE_POSITION ADD CONSTRAINT FK_VEHICLE_POSITION_STOPS_0 FOREIGN KEY ( LAST_STOP_ID ) REFERENCES TRANSPORTATION_HUB.HUB.STOPS( STOP_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE TRANSPORTATION_HUB.HUB.VEHICLE_POSITION ADD CONSTRAINT FK_VEHICLE_POSITION_VEHICLE FOREIGN KEY ( VEHICLE_ID ) REFERENCES TRANSPORTATION_HUB.HUB.VEHICLE( VEHICLE_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;
