CREATE OR REPLACE TABLE TRANSPORTATION_HUB.HUB.VEHICLE (
	VEHICLE_UID NUMBER(38,0) NOT NULL DEFAULT TRANSPORTATION_HUB.HUB.VEHICLE_SEQ.NEXTVAL,
	VEHICLE_ID NUMBER(38,0),
	VEHICLE_TYPE VARCHAR(10),
	CONSTRAINT PK_VEHICLE_ID PRIMARY KEY (VEHICLE_UID)
);