CREATE OR REPLACE SEQUENCE VEHICLE_SEQ START WITH 1 INCREMENT BY 1;

CREATE  TABLE TRANSPORTATION_HUB.HUB.VEHICLES ( 
	VEHICLE_ID           number(38,0) NOT NULL    ,
	VEHICLE_TYPE         varchar(10)     ,
	CONSTRAINT PK_VEHICLE_VEHICLE_ID PRIMARY KEY ( VEHICLE_ID )
 );
