version: 2

sources:
  - name: transport_hub
    database: TRANSPORTATION_HUB  
    schema: STAGING
    tables:
      - name: routes
      - name: route_staging
      - name: vehicle_staging
      - name: VEHICLEENTITIESEXPLODED
      - name: TRIPENTITIESEXPLODEDSTOPSEXPLODED

models:
    - name: routes
      description: "Dimensional table for TriMet routes."
      columns:
        - name: route_id
          description: "ID for a route. Primary key of this table."
          tests:
              - unique
              - not_null
        - name: route_type
          description: "The type of the route."
        - name: route_subtype
          description: "The subtype of the route."
        - name: route_color
          description: "The color of the route."
        - name: route_desc
          description: "A description of the route."

    - name: route_shapes
      description: "Dimensional table for TriMet route shapes for each direction."
      columns:
        - name: route_shape_id
          description: "ID for a route shape. Primary key of this table, generated as a surrogate key of route_id and geography."
          tests:
            - unique
            - not_null
        - name: route_id
          description: "ID for a route."
          tests:
            - not_null
        - name: direction
          description: "Direction on the route, inbound or outbound."
          tests:
            - not_null
        - name: direction_desc
          description: "Description of the direction."
        - name: frequent_service
          description: "Whether the route is considered frequent service."
        - name: geography
          description: "GeoJSON object of the route line shape."
          tests:
            - not_null
                
    - name: vehicles
      description: "Dimensional table for TriMet vehicles"
      columns:
        - name: vehicle_id
          description: "ID for a vehicle. Primary key of this table."
          tests:
              - unique
              - not_null
        - name: vehicle_type
          description: "The type of the vehicle."
        - name: license_plate
          description: "License plate of the vehicle."

    - name: stops
      description: "Dimensional table for TriMet stops."
      columns:
        - name: stop_id
          description: "ID for a stop."
          tests:
            - not_null
        - name: route_id
          description: "ID for a route that the stop belongs to. Foreign key to routes table."
          tests:
              - not_null
              - relationships:
                  to: ref('routes')
                  field: route_id
        - name: stop_desc
          description: "Description for a stop."
        - name: latitude
          description: "Latitude of the stop."
        - name: longitude
          description: "Longitude of the stop."
        - name: route_direction
          description: "Direction on the route the vehicle travels for the stop."
        - name: traffic_direction
          description: "Direction of traffic at the stop as a cardinal direction."       
        - name: stop_sequence
          description: "Sequence of the stop along the route."
        - name: time_point
          description: "Whether the stop is a time point for the route's direction."

    - name: trips
      description: "Dimension table for TriMet trips."
      columns:
        - name: trip_id
          description: "ID for a trip. Primary key of this table."
          tests:
              - unique
              - not_null
        - name: route_id
          description: "ID for the route the trip is travelling."
          tests:
              - not_null
              - relationships:
                  to: ref('routes')
                  field: route_id
        - name: route_direction
          description: "The direction the vehicle travels on the route for the trip."

    - name: trip_delays
      description: "Fact table for trip delays."
      columns:
        - name: trip_delay_id
          description: "ID for the trip delay. Primary key of this table."
          tests:
            - not_null
            - unique
        - name: timestamp
          description: "Timestamp for the trip delay."
          tests:
            - not_null
        - name: trip_id
          description: "ID of the trip."
          tests:
            - not_null
            - relationships:
                to: ref('trips')
                field: trip_id
        - name: trip_stop_sequence
          description: "The sequence of the stop in the trip."
          tests:
            - not_null
        - name: stop_id
          description: "ID of the stop."
          tests:
            - not_null
            - relationships:
                to: ref('stops')
                field: stop_id
        - name: delay
          description: "Delay, in seconds, from the scheduled arrival time to the stop."
    
    - name: vehicle_positions
      description: "Fact table for TriMet vehicle positions."
      columns:
        - name: vehicle_position_id
          description: "ID for the vehicle position. Primary key of this table."
          tests:
            - not_null
            - unique
        - name: timestamp
          description: "Timestamp for the vehicle position."
          tests:
              - not_null
        - name: vehicle_id
          description: "ID of the vehicle."
          tests:
              - not_null

        - name: latitude
          description: "Latitude of the current location the vehicle."
        - name: longitude
          description: "Longitude of the current location the vehicle."
        - name: bearing
          description: "Current bearing of the vehicle."
        - name: speed
          description: "Current speed of the vehicle."
        - name: trip_id
          description: "ID of the trip the vehicle is travelling."
          tests:
              - relationships:
                  to: ref('trips')
                  field: trip_id
        - name: route_id
          description: "ID of the route the vehicle is travelling."
          tests:
              - relationships:
                  to: ref('routes')
                  field: route_id
        - name: stop_id
          description: "ID of the stop the vehicle is stopped at or in transit to."
          tests:
              - relationships:
                  to: ref('stops')
                  field: stop_id
        - name: current_status
          description: "Status of the vehicle, whether it is stopped at or in transit to the current stop ID."
