CREATE OR REPLACE PROCEDURE TRANSPORTATION_HUB.HUB.INSERT_FACT_VEHICLE_POSITION()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS
'
BEGIN
    INSERT INTO HUB.VEHICLE_POSITION (VEHICLE_UID, DATETIME, LATITUDE, LONGITUDE, ROUTE_UID, TRIP_ID, LAST_LOC_ID, NEXT_LOC_ID, LAST_STOP_SEQ, NEXT_STOP_SEQ, IN_CONGESTION, OFF_ROUTE, MESSAGE_UID)
    SELECT
          V.VEHICLE_UID
        , TO_TIMESTAMP_NTZ(TIME, 3)
        , LATITUDE
        , LONGITUDE
        , R.ROUTE_UID
        , TRIPID
        , LASTLOCID
        , NEXTLOCID
        , LASTSTOPSEQ
        , NEXTSTOPSEQ
        , INCONGESTION
        , OFFROUTE
        , M.MESSAGE_UID
    FROM STAGING.VEHICLE_POSITION_STREAM S
    INNER JOIN HUB.VEHICLE V ON V.VEHICLE_ID = S.VEHICLEID
    INNER JOIN HUB.ROUTE R ON R.ROUTE_ID = S.ROUTENUMBER
    INNER JOIN HUB.MESSAGE M ON M.MESSAGE_ID = S.MESSAGECODE;
END;
';