CREATE OR REPLACE PROCEDURE TRANSPORTATION_HUB.HUB.INSERT_DIM_ROUTE()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS 
'
BEGIN
    INSERT INTO TRANSPORTATION_HUB.HUB.ROUTE (ROUTE_ID, ROUTE_TYPE, ROUTE_SUB_TYPE, ROUTE_COLOR, FREQUENT_SERVICE, ROUTE_DESC)
    SELECT DISTINCT
          ID
        , TYPE
        , ROUTESUBTYPE
        , ROUTECOLOR
        , FREQUENTSERVICE
        , DESC
    FROM TRANSPORTATION_HUB.STAGING.ROUTE_STREAM
    WHERE NOT EXISTS (SELECT ROUTE_ID FROM TRANSPORTATION_HUB.HUB.ROUTE WHERE ROUTE_ID = ID);
END;
';