
# Put OpenAI API Key here, if needed

# Snowflake connection info
# use 'authenticator="EXTERNALBROWSER"' instead of 'password=' for SSO login - requires SSO configuration of snowflake account
[connections.snowpark]
user = "RICKBUSCH"
password="***REMOVED***"
warehouse = "COMPUTE_WH"
role = "SYSADMIN"
account = "***REMOVED***"
database = "TRANSPORTATION_HUB"
schema = "HUB"