
# Put OpenAI API Key here, if needed

# Snowflake connection info
# use 'authenticator="EXTERNALBROWSER"' instead of 'password=' for SSO login - requires SSO configuration of snowflake account
[connections.snowpark]
user = "******"
password="******"
warehouse = "COMPUTE_WH"
role = "SYSADMIN"
account = "djfahgs-nab74593"
database = "TRANSPORTATION_HUB"
schema = "HUB"