CREATE OR REPLACE pipe TRANSPORTATION_HUB.STAGING.TRIMET_ROUTES_PIPELINE 
AUTO_INGEST=TRUE 
AS
COPY INTO ROUTE_STAGING
    FROM @TRIMET_S3_STAGE/ROUTECONFIG
    MATCH_BY_COLUMN_NAME='CASE_INSENSITIVE';