CREATE OR REPLACE PIPE TRANSPORTATION_HUB.STAGING.TRIMET_VEHICLE_PIPELINE
AUTO_INGEST=TRUE 
AS
COPY INTO VEHICLE_STAGING
    FROM @TRIMET_S3_STAGE/VEHICLES
    MATCH_BY_COLUMN_NAME='CASE_INSENSITIVE';