CREATE OR REPLACE TASK TRANSPORTATION_HUB.HUB.STAGING_TO_VEHICLE_POSITION
	WAREHOUSE=COMPUTE_WH
	AFTER TRANSPORTATION_HUB.HUB.STAGING_TO_VEHICLE
	WHEN SYSTEM$STREAM_HAS_DATA('STAGING.VEHICLE_POSITION_STREAM')
	AS
    CALL TRANSPORTATION_HUB.HUB.INSERT_FACT_VEHICLE_POSITION();