create or replace view TRANSPORTATION_HUB.HUB.V_TRIP_DELAYS(
	UTC_TIME,
	UTC_TIMESTAMP,
	LOCAL_TIMESTAMP,
	LOCAL_DATE,
	UTC_DATE,
	TRIP_ID,
	TRIP_STOP_SEQUENCE,
	STOP_LOCATION_ID,
	DELAY
) as 
select TIME AS UTC_TIME, TIMESTAMP AS UTC_TIMESTAMP 
,CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', TIMESTAMP) AS LOCAL_TIMESTAMP
,TO_DATE(CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', TIMESTAMP)) as LOCAL_DATE
,TO_DATE(TIMESTAMP) as UTC_DATE
,TRIP_ID, TRIP_STOP_SEQUENCE, STOP_LOCATION_ID, DELAY 
from TRIP_DELAYS
group by TIME, TIMESTAMP, CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', TIMESTAMP)
,CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', TIMESTAMP)
,TO_DATE(CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', TIMESTAMP))
, TRIP_ID, TRIP_STOP_SEQUENCE, STOP_LOCATION_ID, DELAY;