create or replace view VESSEL_STOP_TIME_POSITIONS AS
with tds as (
    select TD.TRIP_ID
        ,TD.LOCAL_DATE
        ,TD.TRIP_STOP_SEQUENCE
        ,TD.STOP_LOCATION_ID
        ,AVG(TD.DELAY) as AVG_DELAY
        from V_TRIP_DELAYS TD
    GROUP BY TD.TRIP_ID
        ,TD.LOCAL_DATE
        ,TD.TRIP_STOP_SEQUENCE
        ,TD.STOP_LOCATION_ID)
select VP.VEHICLE_ID
,V.VEHICLE_TYPE
,VP.TIMESTAMP AS LOCAL_TIMESTAMP
,CONVERT_TIMEZONE('America/Los_Angeles', 'UTC', VP.TIMESTAMP) AS UTC_TIME
,TO_DATE(VP.TIMESTAMP) as LOCAL_DATE
,TO_DATE(CONVERT_TIMEZONE('America/Los_Angeles', 'UTC', VP.TIMESTAMP)) as UTC_DATE
,VP.LATITUDE
,VP.LONGITUDE
,VP.BEARING
,VP.SPEED
,VP.TRIP_ID
,T.ROUTE_ID AS TRIP_ROUTE_ID
,T.ROUTE_DIRECTION as TRIP_ROUTE_DIRECTION
,VP.ROUTE_ID
,R.ROUTE_TYPE
,R.ROUTE_SUBTYPE
,R.ROUTE_DESC
,VP.STOP_LOCATION_ID
,S.STOP_DESC
,S.ROUTE_DIRECTION
,S.STOP_SEQUENCE
,S.TIME_POINT
,VP.CURRENT_STATUS
,ST.ARRIVAL_TIME AS SCHEDULED_ARRIVAL_TIME
,ST.ARRIVAL_TIME AS SCHEDULED_DEPTARTURE_TIME
,TO_TIMESTAMP(TO_CHAR(TO_DATE(VP.TIMESTAMP)||' '||''||ST.ARRIVAL_TIME||'')) AS ARRIVAL_TIME_AS_TIMESTAMP
,TIMEDIFF(SECONDS, TIME(TO_TIMESTAMP(TO_CHAR(TO_DATE(VP.TIMESTAMP)||' '||''||ST.ARRIVAL_TIME||''))), TIME(VP.TIMESTAMP)) AS TIMESTAMP_DELAY
,TDS.AVG_DELAY AS AVG_DELAY
,TIMEADD(SECONDS, (TDS.AVG_DELAY), TIME(VP.TIMESTAMP)) AS PROOF_ARRIVAL_TIME
from HUB.VEHICLE_POSITIONS VP
 join VEHICLES V on VP.VEHICLE_ID = V.VEHICLE_ID
 join ROUTES R on VP.ROUTE_ID = R.ROUTE_ID
 join TRIPS T on VP.TRIP_ID = T.TRIP_ID
 join STOPS S on VP.STOP_LOCATION_ID = S.STOP_LOCATION_ID
    AND VP.ROUTE_ID = S.ROUTE_ID
    AND T.ROUTE_DIRECTION = S.ROUTE_DIRECTION
  join STOP_TIMES ST on T.TRIP_ID = ST.TRIP_ID
      AND S.STOP_LOCATION_ID = ST.STOP_LOCATION_ID
  join TDS on T.TRIP_ID = TDS.TRIP_ID
      AND S.STOP_LOCATION_ID = TDS.STOP_LOCATION_ID
      AND TO_DATE(VP.TIMESTAMP) = TDS.LOCAL_DATE
where VP.CURRENT_STATUS = 'STOPPED_AT'
and S.TIME_POINT = TRUE
order by VP.VEHICLE_ID, VP.TIMESTAMP
;

