FROM cnfldemos/cp-server-connect-datagen:0.5.3-7.1.0
USER root
RUN wget -P /usr/share/confluent-hub-components/confluentinc-kafka-connect-datagen/lib https://repo1.maven.org/maven2/com/snowflake/snowflake-kafka-connector/2.0.0/snowflake-kafka-connector-2.0.0.jar 
RUN wget -P /usr/share/confluent-hub-components/confluentinc-kafka-connect-datagen/lib https://packages.confluent.io/maven/io/confluent/kafka-connect-s3/10.4.2/kafka-connect-s3-10.4.2.jar
RUN wget -P /usr/share/confluent-hub-components/confluentinc-kafka-connect-datagen/lib https://repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk15on/1.70/bcprov-jdk15on-1.70.jar
RUN wget -P /usr/share/confluent-hub-components/confluentinc-kafka-connect-datagen/lib https://repo1.maven.org/maven2/org/bouncycastle/bc-fips/1.0.1/bc-fips-1.0.1.jar
RUN wget -P /usr/share/confluent-hub-components/confluentinc-kafka-connect-datagen/lib https://repo1.maven.org/maven2/org/bouncycastle/bcpkix-fips/1.0.3/bcpkix-fips-1.0.3.jar 
USER appuser
