FROM amazoncorretto:20-alpine-jdk
RUN mkdir /javafiles
COPY pom.xml /javafiles/pom.xml
COPY src/ /javafiles/src/
WORKDIR /javafiles
RUN apk update
RUN apk add maven
RUN mvn clean package 
RUN chmod 755 target/RealtimeStreaming-jar-with-dependencies.jar


